<?php

return array(
	'donations' => 'Donations',
	'point' => 'point',
	'points' => 'points',
	'donate' => 'Donate',
	'donate_points_to' => 'Donate points to ^',
	'donation_point_rates' => 'Donation Point Rates',
	'add_rate' => "Add Rate",
	'add_donation_point_rate' => 'Add Donation Point Rate',
	'edit_donation_point_rate' => 'Edit Donation Point Rate',
	'delete_donation_point_rate' => 'Delete Donation Point Rate',
	'are_you_sure_to_delete_point_rate' => 'Are you sure you want to delete the ^ point rate?',
	'asset_name' => 'Asset name',
	'rate_per_point' => 'Rate per point',
	'add' => 'Add',
	'save' => 'Save',
	'delete' => 'Delete',
	'yes' => 'Yes',
	'no' => 'No',
	'number_of_points_to_donate' => 'Number of points to donate',
	'pay_points_with' => 'Pay your ^ points donation with:',
	'pay_with' => 'Pay with:',
	'at_token_rate_per_point' => '@ ^ per point',
	'pay' => 'Pay',
	'back' => 'Back',
	'please_select_payment' => 'Please select a payment',
	'payment_error_no_txid' => 'Payment error: No TXID',
	'payment_error_invalid_txid' => 'Payment error: Invalid TXID (^)',
	'donated_points_to_user' => 'Donated ^ points to %user',
	'thank_you' => 'Thank you',
);

